name: fhirlite_central
description: Central Micro Server for the FHIR Lite EHR
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  at_client: ^3.0.61
  at_fhir:
    path: ../at_fhir
  at_onboarding_cli: ^1.3.0
  fhir: ^0.11.2
  fhir_at_rest: ^0.11.2
  version: ^3.0.2

dev_dependencies:
  mockito: ^5.4.2

dependency_overrides:
  http: ^1.0.0