name: fhirlite_central
description: Central Micro Server for the FHIR Lite EHR
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  at_client: ^3.0.61
  at_onboarding_cli: ^1.3.0
  at_commons: ^3.0.47
  at_fhir:
    path: ../at_fhir
  # at_utils: ^3.0.13
  fhir: ^0.11.2
  fhir_at_rest: ^0.11.2
  freezed_annotation: ^2.2.0
  # intl: ^0.18.0
  json_annotation: ^4.8.1
  riverpod: ^2.3.6
  shared_preferences: ^2.1.2
  version: ^3.0.2
  # url_launcher: ^6.1.11

dev_dependencies:
  build_runner: ^2.4.5
  freezed: ^2.3.5
  json_serializable: ^6.7.0
  mockito: ^5.4.2

dependency_overrides:
  http: ^1.0.0