name: fhirlite_central
description: Central Micro Server for the FHIR Lite EHR
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  at_client: ^3.0.59
  # at_commons: ^3.0.47
  # at_utils: ^3.0.13
  path_provider: ^2.0.15
  fhir: ^0.11.0
  freezed_annotation: ^2.2.0
  # intl: ^0.18.0
  # json_annotation: ^4.8.1
  shared_preferences: ^2.1.1
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  # url_launcher: ^6.1.11

dev_dependencies:
  build_runner: ^2.4.4
  freezed: ^2.3.4
  # json_serializable: ^6.7.0
